### ISSUE TITLE
Disabling Sounds and Music crashes the game on startup

### ISSUE THREAD

**Issue by GameHerobrine** [paulevsGitch/BetterWeather#1]
Crashes with this exception thrown:
```
java.lang.NullPointerException: Cannot invoke "paulscode.sound.SoundSystem.playing(String)" because "paulevs.betterweather.client.sound.WeatherSounds.soundSystem" is null
	at paulevs.betterweather.client.sound.WeatherSounds.stop(WeatherSounds.java:33)
	at net.minecraft.class_197.handler$zzd000$better_weather$betterweather_onInit(class_197.java:514)
	at net.minecraft.class_197.<init>(class_197.java:48)
	at net.minecraft.client.Minecraft.method_2106(Minecraft.java:389)
	at net.minecraft.client.Minecraft.run(Minecraft.java:716)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by paulevsGitch** [comment]
Fixed in 0.2.0
